
title: Open Coding 
description: "Class of 2027"
owner_name: Neil Chandra
github_username: neil9674 
github_repo: "neil_2027" 
baseurl: "/neil_2027" 
future: true
incremental: true
remote_theme: jekyll/minima@d4d779a
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
minima:
  skin: dark
  social_links:
    - { platform: github, user_url: "https://github.com/open-coding-society" }
    - { platform: x, user_url: "https://x.com/Open_Coding" }
    - { platform: youtube, user_url: "https://www.youtube.com/@OpenCodingSociety" } 
  nav_pages:
    - navigation/section/csse.md
    - navigation/section/csp.md
    - navigation/section/csa.md 
    - navigation/blog.md
    - navigation/search.md